moderneinc/jenkins-ingest

seed.groovy
See https://blogs.itemis.com/en/in-a-nutshell-removing-artifact-messages-from-maven-log-output
=> Suppress logging of maven downloading

repos.csv
Update Apache/Pulsar build to use Java 17
https://github.com/apache/pulsar/blob/c47f2eda42464eca2724c7cbe6f806c051610a4a/pom.xml#L80-L81
=> Update apache/pulsar to use Java 17

list-repos-in-org.sh
Example usage: `./list-repos-in-org.sh -o jenkins-infra`
Output:
```csv
jenkins-infra/INFRA-896,master,,,,,,
jenkins-infra/account-app,main,,,,,,
jenkins-infra/backend-commit-history-parser,master,,,,,,
jenkins-infra/backend-extension-indexer,master,,,,,,
jenkins-infra/backend-jenkins-plugin-info-plugin,master,,,,,,
jenkins-infra/backend-release.rss,master,,,,,,
jenkins-infra/bigquery-uploader,master,,,,,,
jenkins-infra/crawler,master,,,,,,
jenkins-infra/infra-statistics,master,,,,,,
jenkins-infra/ircbot,main,,,,,,
jenkins-infra/java.net-scm-issue-link,master,,,,,,
jenkins-infra/javadoc,master,,,,,,
jenkins-infra/jenkins-codeql,main,,,,,,
jenkins-infra/jira-ldap-syncer,master,,,,,,
jenkins-infra/l10n-server,master,,,,,,
jenkins-infra/merge-all-repo,master,,,,,, …
```
=> Add `list-repos-in-org.sh` script

repos.csv
=> Add diennea/herddb

README.md
Thought to make it easier on the next one to wonder how to ingest a new project.
=> Add workflow and seed job steps to README

repos.csv
Lots of commas there; think I counted correctly.
=> Ingest cobol-samples-repo daily to prevent outdated LSTs

.github/workflows/addGitHubOrganization.yaml
Notices we overwrote in https://github.com/moderneinc/jenkins-ingest/pull/85 ; this fixes that.
=> Unique branch per org PR

add-github-organization.sh, parser/build.gradle, parser/src/main/java/io/moderne/jenkins/ingest/Merger.java, parser/src/test/java/io/moderne/jenkins/ingest/MergerTest.java, repos.csv
As part of https://github.com/moderneinc/moderne-cli/issues/234
=> Merge with Java to skip archived repositories

.github/workflows/addGitHubOrganization.yaml, add-github-organization.sh
=> Make the Java label configurable

repos.csv
[Auto] The arrow-kt GitHub organization is added.
=> [Auto] The arrow-kt GitHub organization is added

repos.csv
[Auto] The Kotlin GitHub organization is added.
=> [Auto] The Kotlin GitHub organization is added

repos.csv
[Auto] The JetBrains GitHub organization is added.
=> [Auto] The JetBrains GitHub organization is added

repos.csv
[Auto] The square GitHub organization is added.
=> [Auto] The square GitHub organization is added

repos.csv
[Auto] The micronaut-projects GitHub organization is added.
=> [Auto] The micronaut-projects GitHub organization is added

repos.csv
[Auto] The freeplane GitHub organization is added.
=> [Auto] The freeplane GitHub organization is added

repos.csv
[Auto] The gradle GitHub organization is added.
=> [Auto] The gradle GitHub organization is added

repos.csv
[Auto] The helidon-io GitHub organization is added.
=> [Auto] The helidon-io GitHub organization is added

repos.csv
[Auto] The graphql-java GitHub organization is added.
=> [Auto] The graphql-java GitHub organization is added

repos.csv
[Auto] The kcctl GitHub organization is added.
=> [Auto] The kcctl GitHub organization is added

repos.csv
Signed-off-by: Jonathan Leitschuh <Jonathan.Leitschuh@gmail.com>
=> Add & Update the Apache organization

repos.csv
Signed-off-by: Jonathan Leitschuh <Jonathan.Leitschuh@gmail.com>
=> Update the `Google` organization list

gradle/wrapper/gradle-wrapper.properties, gradlew.bat
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.gradle.UpdateGradleWrapper?organizationId=TW9kZXJuZQ%3D%3D
=> refactor: Update Gradle wrapper to 8.6

.github/workflows/ci.yml
Use this link to re-run the recipe: https://app.moderne.io/recipes/builder/zyAMEc7mU?organizationId=TW9kZXJuZQ%3D%3D
=> refactor: Rename Gradle GitHub Actions

src/main/java/io/moderne/jenkins/ingest/Merger.java, src/main/java/io/moderne/jenkins/ingest/Parser.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.CommonStaticAnalysis?organizationId=TW9kZXJuZQ%3D%3D
=> refactor: Common static analysis issues
